### PR TITLE
License support

### PR DESCRIPTION
**Pull request by CintiaLopes**
### Description

Adding support to _rest/licenses_ endpoints as requested by customer.

---
#### Check List
- [x] New functionality includes testing
- [ ] New functionality has been documented in the README if applicable
  - [x] New functionality has been thoroughly documented in the examples (please include helpful comments)

### CODE REVIEW

**Review by lhsvobodaj — APPROVED** [review]

**Review by adriane-cardozo — COMMENTED** [review]
Why LicenseClient does not extend DeletableResource and AddableResource?

**Comment by CintiaLopes** [comment]
@adriane-cardozo because they are slightly different from the default methods.
For example the identifier for licenses is `licenseId`, and not `resourceId` as other resouces.

**Review by adriane-cardozo — CHANGES_REQUESTED** [review]
README should not have any changes.
CHANGELOG and endpoints-support should have the diff only.

**Comment by CintiaLopes** [comment]
@adriane-cardozo DONE. 
It was a rebase problem that added those files.

**Review by adriane-cardozo — APPROVED** [review]

**Pull request merged**
